accounts/urls.py
from django.urls import path

from .views import RegistrationView, LoginUserView, DashboardView, activate_view, LogoutView, UpdateProfileView, ResetYourPasswordView, ResetPasswordDoneView, DashBoardFilterView

app_name = 'accounts'
urlpatterns = [  
    
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/edit/', UpdateProfileView.as_view(), name='updateprofile' ),
    path('dashboard/<str:filter>/', DashBoardFilterView.as_view(), name='dashboard_filter'),
    path('activate/<str:uidb64>/<str:token>', activate_view, name='activate'),
    path('reset/', ResetYourPasswordView.as_view(), name='passwordreset'),
    #using specific name uidb64 because we will be using builtin view
    path('reset/confirm/<str:uidb64>/<str:token>/', ResetPasswordDoneView.as_view(), name='passwordresetdone'),
]

payments/urls.py
from django.urls import path


from .views import PaymentIntentView, CheckoutView, PaymentConfirmationWebhook, CheckoutSavedItem

app_name='payments'
urlpatterns = [  
    path('intent/', PaymentIntentView.as_view(), name='intent'),
    path('webhook/', PaymentConfirmationWebhook.as_view(), name='webhook'),
    path('saved/<str:intent>/', CheckoutSavedItem.as_view(), name='saved'),
    path('', CheckoutView.as_view(), name='checkout'),
]

store/urls.py
from django.urls import path

from .views import HomeView, ProductView, CategoryView

#this name should match with that in core's urls namespace
app_name = 'store'
urlpatterns = [  
    path('', HomeView.as_view(), name='home-view'),
    path('<slug:slug>', ProductView.as_view(), name='product-view'),
    path('shop/<slug:slug>', CategoryView.as_view(), name='category-view'),
]

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, AuthenticationForm
from .models import UserBase


class RegistrationForm(forms.Form):

    username = forms.CharField(
        label='Username',
        max_length=90,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter a username.'
            }),
    )

    email = forms.EmailField(
        label='Email',
        max_length=50,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email address.'
            }),
    )

    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter a strong password.'
            }),
    )

    password2 = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your password again.'
            }),
    )

    class Meta:
        model=UserBase
        fields = ['username', 'email', 'password', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']

        if UserBase.objects.filter(email=email).count():
            raise ValidationError('email already in use.')

        self.email = email

        #here email, other fields are not returned because i have written custom
        #save method and accessing email from self.email

    def clean_username(self):
        username = self.cleaned_data['username']

        if UserBase.objects.filter(username=username):
            raise ValidationError('try a different username.')

        if len(username) < 4:
            raise ValidationError('username must be at least 4 characters.')

        self.username = username
        

    #since two password are related field they can be processed in clean together

    def clean(self):
        data = super().clean()

        password = data.get('password')
        password2 = data.get('password2')

        if not password == password2:
            self.add_error(field='password', error='two passwords must match.')

        if len(password) < 8:
            self.add_error(field='password', error='length of password must be between 8 - 16 characters')

        if not any(char.isdigit() for char in password):
            self.add_error(field='password', error='there must be at least 1 digit in password')
        
        if not any(char in ['$', '@', '#', '%', '_', '-', '+'] for char in password):
            self.add_error(field='password', error='there should be at least 1 special symbol($, @, #, %, -, _, +).')

        self.password = password

        return data

    def save(self):
    
        user = UserBase.objects.create_user(
            email=self.email,
            username=self.username,
            password=self.password
        )

        return user


class LoginForm(AuthenticationForm):

    username = forms.EmailField(
        label='Email',
        required=True,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your email.'
            }
        )
    )

    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your password.'
            }
        )
    )


class ProfileUpdateForm(forms.ModelForm):

    firstname = forms.CharField(
        label='Firstname*',
        required=True,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your firstname.'
            }
        )
    )

    lastname = forms.CharField(
        label='Lastname*',
        required=True,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your lastname.'
            }
        )
    )

    about = forms.CharField(
        label='Bio',
        required=False,
        max_length=500,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Write something about yourself.'
            }
        )
    )
    

    line1 = forms.CharField(
        label='Address',
        required=True,
        max_length=99,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your address.'
            }
        )
    )

    city = forms.CharField(
        label='City',
        required=False,
        max_length=99,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your city name.'
            }
        )
    )

    code = forms.CharField(
        label='Postal Code',
        required=True,
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your postal code.'
            }
        )
    )

    country = forms.Select(
        attrs={
            'class': 'form-control'
        }
    )

    phone = forms.CharField(
        label='Phonenumber*',
        required=True,
        max_length=10,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your phone number.'
            }
        )
    )
    
    class Meta:
        model = UserBase
        fields = ['firstname', 'lastname', 'profile', 'about', 'line1', 'city', 'code','country', 'phone']

    def clean_firstname(self):
        firstname = self.cleaned_data['firstname']
        if not len(firstname) > 3:
            raise ValidationError('Firstname must be at least  3 alphabets.')

        return firstname

    
    def clean_lastname(self):
        lastname = self.cleaned_data['lastname']
        if not len(lastname) > 3:
            raise ValidationError('Lastname must be at least 3 alphabets.')

        return lastname

    def clean_phone(self):
        phone = self.cleaned_data['phone']

        if not len(phone) == 10:
            raise ValidationError('Phone number be of 10 digits only.')

        return phone


class ResetYourPasswordForm(PasswordResetForm):
    email = forms.EmailField(
        label='Email',
        required=True,
        widget=forms.EmailInput(
            attrs={
                'autocomplete': 'email',
                'class': 'form-control',
                'placeholder': 'Enter your email here.'
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']

        if not UserBase.objects.filter(email=email, is_active=True).exists():
            raise ValidationError('Please enter a valid email.')

        return email

    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name):

        # for now the reset link will be printed to terminal later it will be sent with celery
        email = context.get('email')
        domain = context.get('domain')
        uid = context.get('uid')
        token = context.get('token')

        url = f"http://{domain}/accounts/reset/confirm/{uid}/{token}/"

        print('\n\n\n')
        print(url)
        print('\n\n\n')



class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'class': 'form-control',
                'placeholder': 'Enter your new password.'
        }),
    )

    new_password2 = forms.CharField(
        label="New password confirmation",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'class': 'form-control',
                'placeholder': 'Enter new password again.'
        }),
    )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import FormView, View
from django.views.generic.list import ListView

from .forms import RegistrationForm, LoginForm, ProfileUpdateForm, ResetYourPasswordForm, PasswordResetConfirmForm
from .tasks import SendVerificationToken
from .models import UserBase
from .token import account_verfication_token

from orders.models import Order



class RegistrationView(FormView):
    form_class = RegistrationForm
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('accounts:login')

    def get(self, request, *args, **kwargs):

        if self.request.user.is_authenticated:
            return redirect(reverse_lazy('accounts:dashboard'))

        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        # the default behaviour is to call form.save() and return httpresponse.

        if form.is_valid():
            user = form.save()

            #activation code required to send for user activation.
            #we will manage this later with celery  for now will print
            SendVerificationToken(request=self.request, user=user)
            #the url in terminal and activate user for testing
            
            messages.success(request=self.request, message='Please check your email for your account verification link. You cannot login unless you are verified.')

            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(request=self.request, message='Please ensure the fields are correct.')
            return redirect(reverse_lazy('accounts:registration'))

class LogoutView(View):
    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('accounts:login'))

class LoginUserView(LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('accounts:dashboard')


class DashboardView(LoginRequiredMixin, ListView):
    template_name = 'accounts/dashboard.html'
    context_object_name = 'order_list'
    paginate_by = 5

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-updated_at')


class DashBoardFilterView(LoginRequiredMixin, ListView):
    template_name = 'accounts/dashboard.html'
    context_object_name = 'order_list'
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        self.filter = kwargs['filter']
        return super().get(request, *args, **kwargs)

  
    def get_queryset(self):
        if self.filter == 'paid':
            return Order.objects.filter(user=self.request.user, billing_status=True).order_by('-updated_at')
        elif self.filter == 'topay':
            return Order.objects.filter(user=self.request.user, billing_status=False).order_by('-updated_at')
        else:
            raise Http404



















def activate_view(request, uidb64, token):
    
    try:
        uid_decoded = force_str(urlsafe_base64_decode(uidb64))
        user = UserBase.objects.get(pk=uid_decoded)

        if user is not None and account_verfication_token.check_token(user=user, token=token):
            user.is_active = True
            user.save()

            return HttpResponseRedirect(reverse_lazy('accounts:login'))

        return HttpResponse(content={'This activation link has expired.'})
    except:
        return HttpResponse(content={'message': 'This activation is not valid.'})



class UpdateProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/updateprofile.html'
    form_class = ProfileUpdateForm
    success_url = reverse_lazy('accounts:dashboard')

    def get_form_kwargs(self):
        data = super().get_form_kwargs()
        data.update({'instance': self.request.user})
        return data
    
    def form_valid(self, form):
        if form.is_valid():
            form.save()
            messages.success(request=self.request, message='Your profile has been updated successfully.')
        
        return super().form_valid(form)



class ResetYourPasswordView(PasswordResetView):
    template_name = 'accounts/passwordreset.html'
    form_class = ResetYourPasswordForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        messages.success(
            request=self.request,
            message="Reset link has been sent to your email. Please change your password then login."
        )
        return super().form_valid(form)
    

class ResetPasswordDoneView(PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/passwordresetconfirm.html'
    form_class = PasswordResetConfirmForm

    def form_valid(self, form):
        messages.success(request=self.request, message='Your password was changed successfully.')
        return super().form_valid(form)

templates/accounts/dashboard.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/accounts/dashboard.css' %}">

<main class="pt-5">
    <div class="container" style="max-width: 1000px;">

        <div class="col-12 row">
            <h2 class="h2 col-8 col-lg-10 fw-normal"> 
                Hi! {{user.username|upper}} 
            </h2>

            {% if user.profile %}
                <img class="col-4 col-lg-2 rounded-circle img-fluid"   src="{{user.profile.url}}">
            {% else %}
                <img class="col rounded-circle img-fluid" style="max-height: 6rem; max-width: 6rem;" src="{% static 'images/defaultprofile.jpg' %}">
            {% endif %}

        </div>

        <div class="col-12 d-flex justify-content-between">
            <div>
                Manage your <b>orders</b> and <b>personal details</b>.
            </div>
            <div>
                <a href="{% url 'accounts:updateprofile' %}">Edit</a>
            </div>
        </div>

        <hr>


        <div class="container">
            <div class="breadcrum h4 fw-normal">
                My Orders
            </div>
            <div class="row mt-5  text-center">
                <a class="text-decoration-none text-dark col-3" href='{% url "accounts:dashboard" %}'><div class=" border-light border-2 border-bottom border-dark border-3" id="all">All</div></a>
                <a class="text-decoration-none text-dark col-3" href='{% url "accounts:dashboard_filter" "paid" %}'><div class=" border-light border-2 border-bottom" id="paid">Paid</div></a>
                <a class="text-decoration-none text-dark col-3" href='{% url "accounts:dashboard_filter" "topay" %}'><div class="border-light border-2 border-bottom" id="topay">To Pay</div></a>
            </div>

            <div class="container-fluid">
            {% if order_list %}

                {% for order in order_list %}

                    <div class="row bg-light my-4 rounded">
                        <div class="col-8">
                            <p class="fw-small mb-0">Order <b>{{order.intent}}</b></p>
                            <div class="fs-6 mt-0">Placed on {{order.created_at}}</div>
                        </div>

                        <div class="col"></div>

                        {% if order.billing_status %}
                            <a role="button" href="#report" class="btn btn-warning col-3 my-1 mx-1">Report a problem</a>
                        {% else %}
                            <a role="button" href="{% url 'payments:saved' order.intent %}" class="btn btn-warning col-3 my-1 mx-1">Pay Now (Rs{{order.total_amount}})</a>
                        {% endif %}


                        <hr>
                        <div class="container-fluid">
                            
                            {% for item in order.items.all %}
                            
                                <div class="row container-fluid my-1">
                                    <div class="col">
                                        {% if item.product.images %}
                                            {% for image in item.product.images.all %}
                                                {% if image.is_featured %}
                                                <img class="img-thumbnail" src="{{image.image.url}}" alt="{{item.product.slug}}">
                                                {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                    </div>
                                    <div class="col">{{item.product.title}}</div>
                                    <div class="col">Qty: <b>{{item.quantity}}</b></div>
                                    
                                    {% if order.billing_status %}
                                        <div class="bg-success col text-center h-25  text-white text-small">Paid</div>
                                    {% else %}
                                        <div class="bg-danger col text-center h-25 text-white ">Unpaid</div>
                                    {% endif %}

                                    <div class="col">Unit price: Rs{{item.unit_price}}</div>
                                    <div class="col">Total: Rs{{item.total_amount}}</div>

                                    {% if order.billing_status %}
                                        <a role="button" href="#review" class="btn btn-secondary col-3 h-25">Review</a>
                                    {% endif %}
                                </div>


                            {% endfor %}

                        </div>
                    </div>
                {% endfor %}


                <div class="container" style="max-width: 1000px;">
        
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                          <li class="page-item">
                            {% if page_obj.has_previous %}
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            {% endif %}
                          </li>
                          {% for page in page_obj.paginator.page_range %}
                          
                            {% if page == page_obj.number %}
                                <li class="page-item active">
                            {% else %}
                                <li class="page-item ">
                            {% endif %}
                                <a class="page-link" href="?page={{ page }}">{{page}}</a>
                            </li>
                          {% endfor %}
                          <li class="page-item">
                            {% if page_obj.has_next %}
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                            {% endif %}
                          </li>
                        </ul>
                      </nav>
                </div>

            {% endif %}
        </div>
        </div>


    </div>

</main>


<script src="{% static 'js/accounts/dashboard.js' %}"></script>
    
{% endblock %}

templates/accounts/login.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    Login
{% endblock %}

{% block content %}

<style>
    ul{
        list-style: none;
    }

    .errorlist{

        padding-left: 0px;
        padding-bottom: 0px;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex py-5 align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">


                            <form method="post" class="rounded mx-auto col-lg-10 p-4">
                                {% csrf_token %}

                                <div class="text-center">
                                    <h2 class="font-weight-bold mb-2">Login</h2>
                                    <p class="mb-4"></p>
                                </div>

                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger align-self-center pb-0" role="alert">{{error}}</div>
                                {% endfor %}
                                {% for field in form %}
                                    
                                    <div class="mt-2">
        
                                        {{field.label}}:
                                        {{field}}
                                    </div>
                                {% endfor %}

                                <p class="row mb-1">
                                    <a class="col-6 text-center" href="{% url 'accounts:passwordreset' %}"><small class="text-muted">Forgot your password?</small></a>
                                    <a class='col-6 text-center' href="#resend"><small class="text-muted">Resend email verification?</small></a>
                                </p>

                                <button type="submit" class="form-control btn btn-primary">Login</button>
                                
                                <p class="text-center mt-2">
                                    <a href="{% url 'accounts:registration' %}">Don't have an account?</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    
{% endblock %}

templates/accounts/passwordreset.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Confirm your email
{% endblock %}


{% block content %}


<style>
    ul{
        list-style: none;
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex py-5 align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">


                            <form method="post" class="rounded mx-auto col-lg-10 p-4">
                                {% csrf_token %}

                                <div class="text-center">
                                    <h2 class="font-weight-bold mb-2">Confirm your email.</h2>
                                    <p class="mb-4">A confirmation link will be sent to your email, click the link to proceed further.</p>
                                </div>
                                

                                {% for field in form %}
                                    
                                    <div class="mt-2">
                                        {% if field.errors %}
                                            <div class="alert alert-danger align-self-center pb-0" role="alert">{{field.errors}}</div>
                                        {% endif %}
                                        {{field.label}}:
                                        {{field}}
                                    </div>
                                {% endfor %}

                                <button type="submit" class="form-control mt-4 btn btn-primary">Confirm</button>
                                
                                <p class="text-center mt-2">
                                    <a href="{% url 'accounts:login' %}">Go back to login.</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/passwordresetconfirm.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Change password
{% endblock %}


{% block content %}


<style>
    ul{
        list-style: none;
    }
</style>

{% if form %}
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex py-5 align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">


                            <form method="post" class="rounded mx-auto col-lg-10 p-4">
                                {% csrf_token %}

                                <div class="text-center">
                                    <h2 class="font-weight-bold mb-2">Change your password.</h2>
                                </div>
                                

                                {% for field in form %}
                                    
                                    <div class="mt-2">
                                        {% if field.errors %}
                                            <div class="alert alert-danger align-self-center pb-0" role="alert">{{field.errors}}</div>
                                        {% endif %}
                                        {{field.label}}:
                                        {{field}}
                                    </div>
                                {% endfor %}

                                <button type="submit" class="form-control mt-4 btn btn-primary">Confirm</button>
                                
                                <p class="text-center mt-2">
                                    <a href="{% url 'accounts:login' %}">Go back to login.</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}

<div class="container vh-100">
    <h5 class="text-center">The password reset link is expired or already used.</h5>
</div>


{% endif %}

{% endblock %}

templates/accounts/registration.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Registration
{% endblock %}


{% block content %}
<style>
    ul{
        list-style: none;
    }

    .errorlist{

        padding-left: 0px;
        padding-bottom: 0px;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex py-5 align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">


                            <form method="post" class="rounded mx-auto col-lg-10 p-4">
                                {% csrf_token %}

                                <div class="text-center">
                                    <h2 class="font-weight-bold mb-2">Create an account.</h2>
                                    <p class="mb-4">It's free and only takes a minute.</p>
                                </div>
                                

                                {% for field in form %}
                                    
                                    <div class="mt-2">
                                        {% if field.errors %}
                                            <div class="alert alert-danger align-self-center pb-0" role="alert">{{field.errors}}</div>
                                        {% endif %}
                                        {{field.label}}:
                                        {{field}}
                                    </div>
                                {% endfor %}

                                <button type="submit" class="form-control mt-4 btn btn-primary">Register</button>
                                
                                <p class="text-center mt-2">
                                    <a href="{% url 'accounts:login' %}">Already have an account?</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}