accounts/urls.py
from django.urls import path

from .views import RegistrationView, LoginUserView, DashboardView, activate_view, LogoutView, UpdateProfileView, ResetYourPasswordView, ResetPasswordDoneView, DashBoardFilterView

app_name = 'accounts'
urlpatterns = [  
    
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/edit/', UpdateProfileView.as_view(), name='updateprofile' ),
    path('dashboard/<str:filter>/', DashBoardFilterView.as_view(), name='dashboard_filter'),
    path('activate/<str:uidb64>/<str:token>', activate_view, name='activate'),
    path('reset/', ResetYourPasswordView.as_view(), name='passwordreset'),
    #using specific name uidb64 because we will be using builtin view
    path('reset/confirm/<str:uidb64>/<str:token>/', ResetPasswordDoneView.as_view(), name='passwordresetdone'),
]

basket/urls.py
from django.urls import path

from .views import BasketSumView, BasketAddView, BasketDeleteView, BasketUpdateView

app_name = 'basket'
urlpatterns = [
    path('', BasketSumView.as_view(), name='basket-sum-view'),
    path('add/', BasketAddView.as_view(), name='basket-add'),
    path('delete/', BasketDeleteView.as_view(), name='basket-delete'),
    path('update/', BasketUpdateView.as_view(), name='basket-update'),
]

store/urls.py
from django.urls import path

from .views import HomeView, ProductView, CategoryView

#this name should match with that in core's urls namespace
app_name = 'store'
urlpatterns = [  
    path('', HomeView.as_view(), name='home-view'),
    path('<slug:slug>', ProductView.as_view(), name='product-view'),
    path('shop/<slug:slug>', CategoryView.as_view(), name='category-view'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%} {% endblock %}</title>

    <!-- static files -->
    <link rel="stylesheet" href="{% static 'css/store/base.css'%}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    
    <!-- for additional style files -->
    {% block styles %} {% endblock %}
  </head>

  <body>
    <!-- <nav class="navbar navbar-expand-lg bg-white">
      <div class="container-fluid shadow-sm pb-1">
        <a class="navbar-brand" href="{% url 'store:home-view' %}">
          Core Ecommerce
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Library
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{% url 'store:home-view' %}"
                    >All</a
                  >
                </li>

                {% for category in category_list %}
                <li>
                  <a
                    href="{{ category.get_absolute_url }}"
                    class="dropdown-item"
                    >{{category}}</a
                  >
                </li>
                {% endfor %}
              </ul>
            </li>
          </ul>
           <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->

            <!-- {% if user.is_authenticated %}
            <a
            href="{% url 'accounts:logout' %}"
            type="button"
            role="button"
            class="btn btn-outline-dark pb-1 mx-1">

            <div>
              Logout
          </div>
           </a>
            {% else %}
            <a
             href="{% url 'accounts:login' %}"
             type="button"
             role="button"
             class="btn btn-outline-dark pb-1 mx-1">

             <div>
              Login
          </div>
            </a>
            {% endif %}

            <a
             href="{% url 'accounts:dashboard' %}"
             type="button"
             role="button"
             class="btn btn-outline-dark pb-1 mx-1">

             <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                  class="bi bi-person" viewBox="0 0 16 16">
                  <path
                      d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
              </svg>
          </div>
            </a>
          <a
            type="button"
            role="button"
            href="{% url 'basket:basket-sum-view' %}"
            class="btn btn-outline-dark pb-1"
          >
            <div class="d-inline-flex align-items-center">
              <div class="total px-1" id="product-count">{{basket|length}}</div>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-cart3"
                viewBox="0 0 16 16"
              >
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
                />
              </svg>
            </div>
          </a>
        </div>
      </div>
    </nav> --> 

    
      <div class="container-fluid">
        <div class="row">
          <nav class="navbar navbar-expand-sm  bg-light"> 
         <div class="col-md-5"> 
        <a class="navbar-brand" href="{% url 'store:home-view' %}">Core Ecommerce</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto">
            <!-- <li class="nav-item">
              <a class="nav-link" href="javascript:void(0)">Link</a>
            </li> -->

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'store:category-view' 'all' %}">All</a>
                {% for category in category_list %}
                <a class="dropdown-item" href="{% url 'store:category-view' slug=category.slug %}">{{category}}</a>
                {% endfor %}
              </div>
            </li>
            
          </ul>
        </div>
        </div>
          <div class="col-md-3"></div>
          <div class="col-md-3">
          <form class="d-flex">
            <input class="form-control me-2" type="text" placeholder="Search">
            <button class="btn btn-primary" type="button">Search</button>
          </form>
        </div>
          <div class="col-md-1  px-1">
            <div class="row">
              <div class="col-md-2">
                
                {% if user.is_authenticated %}
                <a href="{% url 'accounts:login' %}">
                  <i class="fa-solid fa-arrow-right-to-bracket"></i>
                </a>
                {% else %}
                <a href="{% url 'accounts:logout' %}">Sign out</a>
                {% endif %}
              </div>
            
              <div class="col-md-2">
                <a href="{% url 'accounts:dashboard' %}">
                  <i class="fa-solid fa-user"></i>
                </a>
              </div>
              <div class="col-md-2">
                <a href="{% url 'basket:basket-sum-view' %}" class="wrapper">
                  <i class="fa-solid fa-cart-shopping"></i>
                  <span id="basket_count">{{basket|length}}</span>
                </a>
              </div>
              </div>
            </div>
          </div>
      </div>
    </div>
    </nav>

    </div>

    <!-- write your messages here. -->
    <div class="container-fluid row justify-content-center" id="message">

      {% for message in messages %}

        {% if message.tags == 'success' %}
          <div type='button' data-dismiss='alert' class="col-11 text-center alert alert-success alert-dismissible fade show" role="alert">{{message}}</div>
        {% else %}
          <div type='button' data-dismiss='alert' class="col-11 text-center alert alert-danger alert-dismissible fade show" role="alert">{{message}}</div>
        {% endif %}
      {% endfor %}
    </div>
 

    <!-- override this in other templates -->
    {% block content %} {% endblock %}




    <!-- your footer here -->

    
<footer class="container-fluid py-5 bg-light px-5 mt-5">
  <div class="row">
    <div class="col-12 col-md">
      Core Ecommerce
      <small class="d-block mb-3 text-muted">&copy; 2017–2022</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Business</a></li>
        <li><a class="link-secondary" href="#">Education</a></li>
        <li><a class="link-secondary" href="#">Government</a></li>
        <li><a class="link-secondary" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li>
      </ul>
    </div>
  </div>

  <style>
    .wrapper{
      position: relative;
    }
    .wrapper span{
      position: absolute;
      top: -10px;
      right: -8px;
      color: red;
    }


  </style>
</footer>
    <!-- for additional js scripts -->
    {% block scripts %} {% endblock %}
  </body>
</html>