accounts/urls.py
from django.urls import path

from .views import RegistrationView, LoginUserView, DashboardView, activate_view, LogoutView, UpdateProfileView, ResetYourPasswordView, ResetPasswordDoneView, DashBoardFilterView

app_name = 'accounts'
urlpatterns = [  
    
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/edit/', UpdateProfileView.as_view(), name='updateprofile' ),
    path('dashboard/<str:filter>/', DashBoardFilterView.as_view(), name='dashboard_filter'),
    path('activate/<str:uidb64>/<str:token>', activate_view, name='activate'),
    path('reset/', ResetYourPasswordView.as_view(), name='passwordreset'),
    #using specific name uidb64 because we will be using builtin view
    path('reset/confirm/<str:uidb64>/<str:token>/', ResetPasswordDoneView.as_view(), name='passwordresetdone'),
]

basket/urls.py
from django.urls import path

from .views import BasketSumView, BasketAddView, BasketDeleteView, BasketUpdateView

app_name = 'basket'
urlpatterns = [
    path('', BasketSumView.as_view(), name='basket-sum-view'),
    path('add/', BasketAddView.as_view(), name='basket-add'),
    path('delete/', BasketDeleteView.as_view(), name='basket-delete'),
    path('update/', BasketUpdateView.as_view(), name='basket-update'),
]

store/urls.py
from django.urls import path

from .views import HomeView, ProductView, CategoryView

#this name should match with that in core's urls namespace
app_name = 'store'
urlpatterns = [  
    path('', HomeView.as_view(), name='home-view'),
    path('<slug:slug>', ProductView.as_view(), name='product-view'),
    path('shop/<slug:slug>', CategoryView.as_view(), name='category-view'),
]

store/models.py
from django.db import models
from django.urls import reverse

from mptt.models import TreeForeignKey, MPTTModel

from .validators import validate_max_image_size


class Category(MPTTModel):
    """Category is implemented with mptt so we can have dynamic relations between
        categories like tree
    """
    name = models.CharField(
        max_length=255,
        unique=True,

        verbose_name='Category Name',
        help_text='The category name must be unique.',
    )

    slug = models.SlugField(
        max_length=255,
        unique=True,

    )

    #the nodes on tree will have parents, we will set parent to self
    #so that we can build category tree
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
    )

    is_active = models.BooleanField(default=True)

    #documentation says we need this
    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name_plural= 'Categories'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse(
            'store:category-view',
            kwargs={'slug': self.slug},
        )


class ProductType(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
    )

    is_active = models.BooleanField(
        default=True
    )

    class Meta:
        verbose_name = 'Product Type'
        verbose_name_plural = 'Product Types'

    def __str__(self):
        return self.name

class ProductSpecification(models.Model):
    """
    This contains the feature of product it is associated with. Like isbn, pages, etc.
    And it is liked with product type so all product type will have its own features.
    """

    name = models.CharField(
        max_length=255,
    )

    product_type = models.ForeignKey(
        'ProductType',
        on_delete=models.RESTRICT,
        related_name='specifications'
    )

    class Meta:
        verbose_name = 'Product Specification'
        verbose_name_plural = 'Product Specifications'

    def __str__(self):
        return self.name


class Product(models.Model):
    """
        This model is the actual product that has categories, product types, images
    """

    product_type = models.ForeignKey(
        ProductType,
        on_delete=models.RESTRICT,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.RESTRICT,
        related_name='product'
    )


    title = models.CharField(
        max_length=255,
    )
    description = models.TextField(
        blank=True,   
    )
    slug = models.SlugField(
        max_length=255,
    )

    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        help_text='Price in Nepalese Rupees.',
    )


    is_active = models.BooleanField(
        default=True,
    )
    in_stock = models.BooleanField(
        default=True,
    )


    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )


    class Meta:
        ordering = ['updated_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product-view', kwargs={'slug': self.slug})



class ProductSpecificationValue(models.Model):
    """
        This model is for some product with specific features. Like a book with lucky draw inside.
    """

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='specification_value'
    )
    specification = models.ForeignKey(
        ProductSpecification,
        on_delete=models.RESTRICT,
    )


    value = models.CharField(
        max_length=255,
        help_text='The product specific value in less than 255 words.'
    )

    class Meta:
        verbose_name = 'Product Specification Value'
        verbose_name_plural = 'Product Specification Values'

    def __str__(self):
        return self.value



class ProductImage(models.Model):
    """
        A single product may have multiple images, so we store multiple images with a featured image here.
    """

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='images',
    )

    image = models.ImageField(
        upload_to=f'product/',
        default='product/default.png',
        validators=[validate_max_image_size],
    )

    is_featured = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'

    

store/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Category, Product, ProductImage


#access this from setting templates context to send this to all pages

class HomeView(ListView):
    context_object_name = 'product_list'
    paginate_by = 10
    template_name = 'store/home-view.html'
    queryset = Product.objects.all().order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['images'] = ProductImage.objects.all()
        return context


class ProductView(DetailView):
    context_object_name = 'product'
    template_name = 'store/product-view.html'

    def get_queryset(self):
        return Product.objects.filter(slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_tree'] = Category.objects.filter(product__slug=self.kwargs.get('slug')).get_ancestors(include_self=True)
        return context

class CategoryView(ListView):
    context_object_name = 'product_list'
    template_name = 'store/category-view.html'

    def get_queryset(self):
        #we need to return children under the category name too.
        if self.kwargs.get('slug') == 'all':
            categories = Category.objects.filter().get_descendants(include_self=True)
        else:
            categories = Category.objects.filter(slug=self.kwargs.get('slug')).get_descendants(include_self=True)
        return Product.objects.filter(category__name__in=[str(name) for name in categories])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_tree'] = Category.objects.filter(slug=self.kwargs.get('slug')).get_ancestors(include_self=True)
        return context

templates/store/category-view.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    Core Ecommerce
{% endblock %}

{% block styles %}
{% endblock%}

{% block content %}
{% load mptt_tags %}


<div class="position-relative overflow-hidden bg-light">


  <div class="album py-5 bg-white">
    <div class="container">
    
      <div class="d-flex">
      <p>Categories </p>
        <div class="btn"></div>
      <nav 
    style="--bs-breadcrumb-divider: '>';" 
    aria-label="breadcrumb"
    >
      <ol class="breadcrumb">
        {% recursetree category_tree %}
        {% if not node.is_leaft_node %}
        <a class="text-decoration-none breadcrumb-item text-primary" href="{% url 'store:category-view' slug=node.slug %}">{{ node.name }}</a>
        <li class="breadcrumb-item"><a class="text-decoration-none text-primary">{{ children }}</a></li>
        {% endif %}
        {% endrecursetree %}
        <li>{{product.title|truncatechars:20}}</li>
      </ol>
    </nav>
    </div>


      <div class="row">

        {% for product in product_list%}
            <div class="col-lg-3 col-sm-4 my-1">
            <div class="card mb-4 box-shadow h-100">
                {% if product.images %}
                  {% for image in product.images.all %}
                    {% if image.is_featured %}
                        <img class="card-img-top h-75"  src="{{ image.image.url }}" alt="Card image cap">
                    {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="card-body h-30">
                <p class="card-text">{{product.title}}</p>
                <div class="d-flex justify-content-between">
                    <div class="btn-group">
                    <a role='button' class="text-decoration-none text-dark btn btn-sm btn-outline-secondary" href="{{ product.get_absolute_url }}">Learn More</a>
                    </div>
                    <small class="text-muted">Rs. {{product.price}}</small>
                </div>
                </div>
            </div>
            </div>
        {% endfor %}

      </div>

</div>




{% endblock %}

{% block scripts %}
{% endblock %}

templates/store/home-view.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    Core Ecommerce
{% endblock %}

{% block styles %}
{% endblock%}

{% block content %}

<div class="position-relative overflow-hidden text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      
      {% if not user.is_authenticated %}
      <h1 class="display-10 fw-normal">Search, Buy, Review</h1>
      <p class="lead fw-normal px-3">Find your joy with us. Your go to shop for digital goods.</p>
          <a class="btn btn-outline-secondary" href="{% url 'accounts:registration' %}">Make an account</a>
      {% else %}
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for image in images %}
          {% if forloop.first %}
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">{{forloop.counter0}}</li>
          {% else %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}">{{forloop.counter0}}</li>
          {% endif %}
          {% endfor %}
        </ol>
        <div class="carousel-inner">
          {% for image in images %}
          <div class="carousel-item active">
            <img class="d-block w-100" src="{{image.image.url}}" alt="First slide">
          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      {% endif %}
    </div>
    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  </div>



  <div class="album py-5 bg-white">
    <div class="container">
        <h1 class="pb-4 fw-normal">Popular</h1>
      <div class="row">

        {% for product in product_list%}
            <div class="col-lg-3 col-sm-4 my-1">
            <div class="card mb-4 box-shadow h-100">
                {% if product.images %}
                  {% for image in product.images.all %}
                    {% if image.is_featured %}
                        <img class="card-img-top h-75"  src="{{ image.image.url }}" alt="Card image cap">
                    {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="card-body h-30">
                <p class="card-text">{{product.title}}</p>
                <div class="d-flex justify-content-between">
                    <div class="btn-group">
                    <a role='button' class="text-decoration-none text-dark btn btn-sm btn-outline-secondary" href="{{ product.get_absolute_url }}">Learn More</a>
                    </div>
                    <small class="text-muted">Rs. {{product.price}}</small>
                </div>
                </div>
            </div>
            </div>
        {% endfor %}

      </div>
    </div>
  </div>



{% endblock %}

{% block scripts %}
{% endblock %}

templates/store/product-view.html
{% extends '../base.html' %}

{% load static %}

{% block title %} {{product.title | title }} {% endblock %} 

{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}


{% block content %}

{% load mptt_tags %}

<div class="container bg-light mt-5 mx-lg-5 mx-sm-0">
    <nav 
    style="--bs-breadcrumb-divider: '>';" 
    aria-label="breadcrumb"
    >
      <ol class="breadcrumb">
        {% recursetree category_tree %}
        {% if not node.is_leaft_node %}
        <a class="text-decoration-none breadcrumb-item text-primary" href="{% url 'store:category-view' slug=node.slug %}">{{ node.name }}</a>
        <li class="breadcrumb-item"><a class="text-decoration-none text-primary">{{ children }}</a></li>
        {% endif %}
        {% endrecursetree %}
        <li>{{product.title|truncatechars:20}}</li>
      </ol>
    </nav>

    <div class="row pb-2">
        <div class="col-sm-12 col-lg-5">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              {% if product.images %}
                {% for image in product.images.all %}
                  {% if image.is_featured %}
                    <div class="carousel-item active">
                        <img class="d-block max-width-100" src="{{image.image.url}}" style="height: 350px;">
                    </div>
                  {% else %}
                    <div class="carousel-item ">
                      <img src="{{image.image.url}}" style="height: 350px;" class="d-block max-width-100">
                    </div>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </div>
            <a class="carousel-control-prev" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
          </div>
        </div>
        <!-- everything to display in right side should be inside this col -->
        <div class="col">

          <div class="container-fluid row"></div>
          <h2 class="col-12 fw-normal">{{product.title}}</h2>
          <div class="col-12 d-flex justify-content-between">
            <small class="text-muted">Rating:
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
            </small>
            {% if product.in_stock %}
              <small class="text-success">Available</small>
            {% else %}
              <small class="text-danger">Out of stock</small>
            {% endif %}
          </div>

          <hr>

          <div class="col-12 h2 fw-normal text-success d-flex justify-content-between">
            <div>
              Rs. {{product.price}}
            </div>
            <div role="button" class="btn-secondary" data-toggle="collapse" href="#sharelinks">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share mx-3 " viewBox="0 0 16 16">
                <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5zm-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/>
              </svg>
            </div>
          </div>

          <div class="col-12 collapse" id="sharelinks">
            <div class="d-flex justify-content-between">
              <span></span>
              <div>
                <a href="#facebook" class="mx-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
                </a>
                <a href="#twitter" class="mx-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                  </svg>
                </a>
                <a href="#instagram" class="mx-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                  </svg>
                </a>
              </div>
            </div>
          </div>

          

          <div class="col-12">

            <div>
              {{product.description}}
            </div>

                <div class=" d-flex mt-5 mb-1 justify-content-between">
                  <div>
                    <label for="select">Quantity</label>
                      <select name="quantity" id="select">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                      </select>
                  </div>

                    {% if product.in_stock %}
                      <button
                        type="button"
                        class="btn btn-secondary btn-sm"
                        id="cart"
                        value="{{product.pk}}"
                      >
                        Add to Cart
                      </button>
                    {% else %}
                      <button
                      type="button"
                      class="btn btn-secondary btn-sm"
                      id="wishlist"
                      value="{{product.pk}}"
                    >
                      Add to Wishlist
                    </button>
                    {% endif %}
                </div>
            </div>

            </div>
        </div>
      </div>
    </div>
  </div>
</div> 

    </div>
  </div>
</div>  


<!-- product specifications -->
<div class="container bg-light mt-3 py-2 mx-lg-5 mx-sm-0">
  <h6 class="fw-normal">Specifications of {{product.title}}</h6>
  <ul>
    {% for specification in product.specification_value.all %}
      <li>{{specification.specification.name}} - {{specification.value}}</li>
    {% endfor %}
  </ul>
</div>  

<!-- rating and review -->
<div class="container bg-light mt-3 py-2 mx-lg-5 mx-sm-0">
  <h6 class="fw-normal">Ratings & Reviews of {{product.title}}</h6>

</div>

<style>
  .checked {
  color: orange;
}
</style>




<script>
    let cart = document.getElementById('cart')
    let items = document.getElementById('select')
    let count = document.getElementById('basket_count')

    if(cart){
      cart.onclick = () => {
      
      data = {
          'product_id': cart.value,
          'product_count': items.value,
      }

      fetch("{% url 'basket:basket-add' %}",
          {
              method: "POST",
              body: JSON.stringify(data),
              headers: { "X-CSRFToken": '{{csrf_token}}' },
          }
      ).then(res => res.json()).then(data => {
          count.innerHTML = data['count']

          let message = document.getElementById('message')
          message.innerHTML = `<div type='button' data-dismiss='alert' class="col-11 text-center alert alert-success alert-dismissible fade show" role="alert">${data['title']} is added to cart.</div>`;
            
      });
}

    }
   
</script>

{% endblock %}