basket/urls.py
from django.urls import path

from .views import BasketSumView, BasketAddView, BasketDeleteView, BasketUpdateView

app_name = 'basket'
urlpatterns = [
    path('', BasketSumView.as_view(), name='basket-sum-view'),
    path('add/', BasketAddView.as_view(), name='basket-add'),
    path('delete/', BasketDeleteView.as_view(), name='basket-delete'),
    path('update/', BasketUpdateView.as_view(), name='basket-update'),
]

orders/urls.py
from django.urls import path


from .views import OrderAddView, OrderSaveView

app_name = 'orders'
urlpatterns = [  
    path('add/', OrderAddView.as_view(), name='add'),
    path('save/', OrderSaveView.as_view(), name='save'),
]

payments/urls.py
from django.urls import path


from .views import PaymentIntentView, CheckoutView, PaymentConfirmationWebhook, CheckoutSavedItem

app_name='payments'
urlpatterns = [  
    path('intent/', PaymentIntentView.as_view(), name='intent'),
    path('webhook/', PaymentConfirmationWebhook.as_view(), name='webhook'),
    path('saved/<str:intent>/', CheckoutSavedItem.as_view(), name='saved'),
    path('', CheckoutView.as_view(), name='checkout'),
]

store/urls.py
from django.urls import path

from .views import HomeView, ProductView, CategoryView

#this name should match with that in core's urls namespace
app_name = 'store'
urlpatterns = [  
    path('', HomeView.as_view(), name='home-view'),
    path('<slug:slug>', ProductView.as_view(), name='product-view'),
    path('shop/<slug:slug>', CategoryView.as_view(), name='category-view'),
]

basket/views.py
from django.views.generic.base import TemplateView
from django.views import View
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages

from store.models import Product
from .basket import BasketSessions
import json



class BasketSumView(TemplateView):
    template_name = 'basket/basket-sum-view.html'

class BasketAddView(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        product_id = int(data.get('product_id'))
        product_count = int(data.get('product_count'))

        basket = BasketSessions(request)
        product = get_object_or_404(Product, pk=product_id)
        count = basket.addSessionData(
            product=product,
            count=product_count
        )

        return JsonResponse({'count': count, 'title': str(product)})

class BasketUpdateView(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        product_id = int(data.get('product_id'))
        product_count = int(data.get('product_count'))

        basket = BasketSessions(request)
        product = get_object_or_404(Product, pk=product_id)
        data = basket.updateSessionData(
            product=product,
            count=product_count
        )

        data['title'] = str(product)
        return JsonResponse(data)

class BasketDeleteView(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        product_id = int(data.get('product_id'))

        basket = BasketSessions(request)
        if data:=basket.deleteSessionData(product_id):
            data['title'] = str(get_object_or_404(Product, pk=product_id))
            data['delete'] = 'ok'
            return JsonResponse(data)
        else:
            return JsonResponse({'delete': 'false'})

templates/basket/basket-sum-view.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Cart
{% endblock %}


{% block content %}


<main class="pt-5">
    <div class="container">
        <div class="row">
            <div class="col-6 h4">Shopping Cart</div>
            <div class="col-6 text-end h4">
                <span id="total_price">Total: Rs {{basket.getTotalPrice}}</span>
            </div>
        </div>
        <hr />

        {% if basket|length %}
          <div class="row" id="checkout">
            <div class="col-6">
              <div></div>
            </div>
          <div class="col-6 row">
              <a role="button" href="{% url 'payments:intent' %}" class="btn btn-success fw-bold col-6" type="button">Checkout</a>
              <button onclick="save_order()" class="btn btn-light col-6" type="button">Save for later</button>
          </div>
          </div>
        {% endif %}

        <div id="container_products">
        {% for item in basket %}

            {% with product=item.product %}

            <div class="container pt-sm-0 pt-md-5" id="container_{{product.id}}">
                <div class="pt-2">
                  <div class="row g-3 bg-light py-1">
                    <div class="col-md-5 col-lg-5 order-md-first bg-light">
                      {% if product.images %}
                        {% for image in product.images.all %}
                          {% if image.is_featured %}
                            <div class="carousel-item active">
                                <img class="d-block" src="{{image.image.url}}" style="height: 200px;">
                            </div>
                          {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>
                    <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                      <h1 class="mb-0 h4 fw-normal">{{ product.title }}</h1>
                      
              
                      <div class="border">
                        <div class="col border-bottom">
                          <div class="row p-3">
                            <div class="col-6">Digital</div>
                            <div class="col-6 text-end">
                                <span>Unit </span>
                              <span>Rs.{{ item.price }}</span>
                            </div>
                          </div>
                        </div>
              
                        <div class="col">
                          <div class="row p-3">
                            <div class="col-2">
                              <label for="select">Qty</label>
                                <select name="quantity" id="select_{{product.id}}">
                                  <option selected>{{item.count}}</option>
                                  <option value="1">1</option>
                                  <option value="2">2</option>
                                  <option value="3">3</option>
                                  <option value="4">4</option>
                                </select>
                            </div>

                            <div class="col-3">
                                <span>Total</span>
                                <span id="sub_total_{{product.id}}">Rs {{item.total_price}}</span>
                            </div>
              
                            <div class="col text-end">
                                <button
                                type="button"
                                class="btn btn-secondary btn-sm"
                                value="{{product.id}}"

                                onclick="UpdateFunction(value)"
                              >
                                Update
                              </button>
                              <button
                                type="button"
                                class="btn btn-secondary btn-sm"
                                value="{{product.id}}"

                                onclick="DeleteFunction(value)"
                              >
                                Delete
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
            {% endwith %}
        {% endfor %}
      </div>

    </div>

</main>
{% endblock %}


{% block scripts %}

<script>

  UpdateFunction = (value) => {
    let items = document.getElementById('select_' + value)
    let checkout = document.getElementById('checkout')
    let count = document.getElementById('basket_count')
    let total = document.getElementById('total_price')
    let message = document.getElementById('message')
    let save = document.getElementById('save')


    data = {
        'product_id': value,
        'product_count': items.value,
      }

      fetch("{% url 'basket:basket-update' %}",
      {
        method: "POST",
        body: JSON.stringify(data),
        headers: { "X-CSRFToken": '{{csrf_token}}' },
      }).then( res => res.json()).then( data => {

        let sub_total = document.getElementById('sub_total_' + value)
        
        message.innerHTML = `<div type='button' data-dismiss='alert' class="col-11 text-center alert alert-success alert-dismissible fade show" role="alert">${data['title']} is successfully updated.</div>`;

        count.innerHTML = data['count']
        total.innerText = "Total: Rs " + data['total_price']
        sub_total.innerHTML = "Rs " + data['sub_price']

      })

  }

  DeleteFunction = (value) =>{

    let total = document.getElementById('total_price')
    let message = document.getElementById('message')


      data = {
        'product_id': value
      }

      fetch("{% url 'basket:basket-delete' %}",
      {
        method: "POST",
        body: JSON.stringify(data),
        headers: { "X-CSRFToken": '{{csrf_token}}' },
      }).then( res => res.json()).then( data => {

        if( data['delete'] == 'ok'){
          let count = document.getElementById('basket_count')
          let container = document.getElementById('container_' + value )
          container.textContent = ''
          container.remove()

          count.innerText = data['count']
          total.innerText = "Total: Rs " + data['total_price']

          message.innerHTML = `<div type='button' data-dismiss='alert' class="col-11 text-center alert alert-danger alert-dismissible fade show" role="alert">${data['title']} is removed form cart.</div>`;
             
          if(!data['count']){
            checkout.innerHTML = ''
        }
        }
      })
  }


save_order = () => {
  let count = document.getElementById('product-count')
  let products = document.getElementById('container_products');
  let total = document.getElementById('total_price')


  fetch(
    "{% url 'orders:save' %}",{
      method: "GET",
      headers: { "X-CSRFToken": '{{csrf_token}}' },
    }
  ).then(res => res.json())
  .then(data => { 
    if( data['success'] == 'ok'){
        total.innerText = "Total: Rs " + '0';
        count.innerText = 0
        checkout.innerHTML = ''
        products.innerText = ''
        message.innerHTML = `<div type='button' data-dismiss='alert' class="col-11 text-center alert alert-success alert-dismissible fade show" role="alert">${data['message']}</div>`;
      }
  })
  .catch( ()=> { 
    message.innerHTML = `<div type='button' data-dismiss='alert' class="col-11 text-center alert alert-danger alert-dismissible fade show" role="alert">You need to login to save orders for later.</div>`;
  })

  
}

</script>
{% endblock %}